# This is a basic workflow to help you get started with Actions

name: Build Data

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  # Pausing the build on pull_request because it seems these cause a duplicate build which can fail.
  # I added this event because it seemed sometimes `push` was not causing a build.
  # So I'm leaving these comments until it's verified that `push` alone is good.
  #pull_request:
  #  types: [ closed ]
  #  branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt

    - name: Run unit tests with pytest
      run: |
        cd tools
        pytest
        cd ..

    - name: Create json csv md files
      run: python tools/data_builder.py

    # Deploy data to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: data_build
        FOLDER: tools/data_build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
